baseURL = 'https://7Cuba7.github.io/'
locale = 'en-us'
title = 'Tauro tinklalapis'
theme = 'PaperMod'
[menu]
  [[menu.main]]
    identifier = "about"
    name = "Apie"
    url = "/about/"
    weight = 10